### ISSUE TITLE
Only allow access to the dashboard if a valid blockchain name exists

### ISSUE THREAD

**Issue by abungay** [talos-org/client#25]
~We should store a flag and the name of the current blockchain in the MobX state, and only show the onboarding page first if we don't currently have a blockchain in our store/the flag is not set.~

Related https://github.com/talos-org/client/pull/43#issuecomment-451279094.

**Comment by yeskunall** [comment]
I see this is specific to the demo. We don’t need to use MobX for this. Simply use component state to do this. So, for example, if you were doing this using MobX in parent container X, instead just use `X.state` and pass it along as a prop to its children.

Learning MobX is a task on its own. Don’t waste time on learning MobX right now, not for _this_ purpose.

**Comment by yeskunall** [comment]
Also, for the future: think twice before creating issues. This didn’t need to be an issue. This is clearly a user story. This should have been part of a design document, like the one [here](https://paper.dropbox.com/doc/Design-Checklist--ASPqR6xBKhxInFslumt~csu3AQ-aWD2Uxfg3mnxJ1VQkJaKB).

The design checklist needs to be updated by @talos-org/all as we come up with new user stories. Don’t forget about this document @talos-org/back-end because @talos-org/front-end will be using that document to convert user stories into actionable tasks. Stuff like https://github.com/talos-org/client/issues/21#issuecomment-439742500 should really have been addressed in that design checklist document.

If we fall back on that document, @talos-org/front-end can’t guarantee any consistency between user stories and our UI. That’s just how it’s gonna work.

**Comment by yeskunall** [comment]
Reopening as it hasn’t been fixed—as in merged into `master` yet.
